import { PROJECTS, TALKS, WRITING, BLOGS } from "@/lib/content";
import { chipColorFor, CHIP_PALETTE } from "@/lib/chipColor";
import { TALK_CLIPS } from "./talkClips";
import { LQIP } from "@/generated/lqip";
import type { Item } from "@/lib/types";

// Media pulled from the real site content so the lab scenes show actual work,
// rendered as the same card types the home page uses (projects, talks,
// articles). Project clips play as local video; talks/articles use their cover
// image, self-hosted under /lab-media so textures never hit a CORS wall or
// depend on an external host (see scripts/gen-lab-media.sh).

export type LabKind = "project" | "talk" | "writing" | "blog";

export interface LabMedia {
  src: string;
  // H.264 MP4 fallback when `src` is a WebM video (Safari / Vision Pro)
  srcFallback?: string;
  // still image shown when the card is not the focused one, so only a few
  // videos decode at a time
  poster?: string;
  // tiny blurred placeholder shown while the card media loads
  lqip?: string;
  // USDZ card for the <model> element (true 3D on Apple Vision Pro)
  usdz?: string;
  slug: string;
  title: string;
  kicker: string;
  desc: string;
  tags?: string[];
  color: string;
  kind: LabKind;
  video: boolean;
  // project shelf ("side" = fun side projects, shown separately on the tab)
  group?: string;
}

// Same colored-kicker logic as the site cards, with a palette fallback so every
// lab card gets a chip color even for kickers without a fixed mapping.
const colorFor = (p: Item, i: number): string =>
  p.kickerColor ?? chipColorFor(p.kicker) ?? CHIP_PALETTE[i % CHIP_PALETTE.length];

// Home/hero project media is a compact, self-hosted preview (a tiny H.264 MP4 +
// crisp webp poster, generated by scripts/gen-previews.mjs). The MP4 is decoded
// frame-by-frame into a <canvas> via WebCodecs (no <video>, so Safari autoplay
// never applies) -- never the full multi-MB cover video, which only the item
// page loads.
function projectMedia(p: Item, i: number): LabMedia {
  return {
    src: `/previews/${p.slug}.mp4`,
    poster: `/previews/${p.slug}.webp`,
    usdz: `/models/${p.slug}/card.usdz`,
    slug: p.slug,
    title: p.title,
    kicker: p.kicker,
    desc: p.desc,
    tags: p.tags,
    color: colorFor(p, i),
    kind: "project",
    video: true,
    group: p.group,
  };
}

function staticMedia(p: Item, i: number, kind: LabKind, dir: string): LabMedia {
  const src = `/lab-media/${dir}/${p.slug}.webp`;
  return {
    src,
    lqip: LQIP[src],
    usdz: `/lab-media/${dir}/${p.slug}.usdz`,
    slug: p.slug,
    title: p.title,
    kicker: p.kicker,
    desc: p.desc,
    color: colorFor(p, i),
    kind,
    video: false,
  };
}

// Talks play a self-hosted preview clip where we have one, else fall back to the
// static thumbnail.
function talkMedia(p: Item, i: number): LabMedia {
  if (TALK_CLIPS.has(p.slug)) {
    return {
      src: `/previews/${p.slug}.mp4`,
      poster: `/previews/${p.slug}.webp`,
      usdz: `/lab-media/talks/${p.slug}.usdz`,
      slug: p.slug,
      title: p.title,
      kicker: p.kicker,
      desc: p.desc,
      color: colorFor(p, i),
      kind: "talk",
      video: true,
    };
  }
  return staticMedia(p, i, "talk", "talks");
}

// Blog cards: a post with a live demo gets a MOTION preview (a tiny H.264 clip of the real thing,
// decoded to canvas like a project card, with a real-screenshot poster at /previews/<slug>.webp).
// Body-only posts fall back to a static cover under /lab-media/blog.
function blogMedia(p: Item, i: number): LabMedia {
  if (p.demo || p.preview) {
    return {
      src: `/previews/${p.slug}.mp4`,
      poster: `/previews/${p.slug}.webp`,
      slug: p.slug,
      title: p.title,
      kicker: p.kicker,
      desc: p.desc,
      tags: p.tags,
      color: colorFor(p, i),
      kind: "blog",
      video: true,
    };
  }
  return staticMedia(p, i, "blog", "blog");
}

function interleave<T>(...lists: T[][]): T[] {
  const out: T[] = [];
  const max = Math.max(0, ...lists.map((l) => l.length));
  for (let i = 0; i < max; i++) {
    for (const l of lists) if (i < l.length) out.push(l[i]);
  }
  return out;
}

const projects = PROJECTS.map(projectMedia).slice(0, 6);
const talks = TALKS.map(talkMedia).slice(0, 6);
const articles = WRITING.map((p, i) => staticMedia(p, i, "writing", "writing")).slice(
  0,
  6,
);

// One deck mixing all three card types, round-robin so each lab scene shows a
// bit of everything (projects play video here).
export const labDeck: LabMedia[] = interleave(projects, talks, articles);

// Per-type decks for the home work galleries (featured items, like the home
// page). Projects play video; talks and articles use their self-hosted cover
// image. Keeping the projects deck to the featured set bounds how many video
// elements load at once.
const featuredOf = <T extends { featured?: boolean }>(list: T[]): T[] => {
  const f = list.filter((x) => x.featured);
  return f.length ? f : list;
};

export const labProjects: LabMedia[] = featuredOf(PROJECTS.filter((p) => p.group !== "dns")).map(projectMedia);
export const labTalks: LabMedia[] = featuredOf(TALKS).map(talkMedia);
export const labArticles: LabMedia[] = featuredOf(WRITING).map((p, i) =>
  staticMedia(p, i, "writing", "writing"),
);
// Blog (side-projects / demos): demo posts play a real motion preview, body-only posts a cover.
export const labBlog: LabMedia[] = featuredOf(BLOGS).map(blogMedia);

// Full per-kind decks for the tab pages: the home's featured items first (same
// cards, same order, so the home->tab transition reads as "your cards moved
// into place"), then everything else.
const featuredFirst = <T extends { featured?: boolean }>(list: T[]): T[] => {
  const f = list.filter((x) => x.featured);
  if (!f.length) return list;
  return [...f, ...list.filter((x) => !x.featured)];
};

export const labAll: Record<LabKind, LabMedia[]> = {
  project: featuredFirst(PROJECTS.filter((p) => p.group !== "dns")).map(projectMedia),
  talk: featuredFirst(TALKS).map(talkMedia),
  writing: featuredFirst(WRITING).map((p, i) =>
    staticMedia(p, i, "writing", "writing"),
  ),
  blog: featuredFirst(BLOGS).map(blogMedia),
};
